"""Regression tests for the installed `marsha` launcher templates.

The launcher (generated by make_launcher.py from marsha.sh.in / marsha.bat.in) must run the
venv's python with -P (PEP 670). Without it, `python -m marsha` puts the current working
directory on sys.path, so running `marsha` from inside a source checkout silently uses that
checkout's `marsha/` package instead of the installed version in the venv.
"""

import os

# The templates live at the repository root, one level up from this tests/ directory.
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _template(name: str) -> str:
    with open(os.path.join(REPO, name)) as f:
        return f.read()


def test_sh_launcher_uses_safe_path_flag() -> None:
    # -P must precede `-m marsha` so the CWD is not added to the module search path.
    text = _template('marsha.sh.in')
    assert '-P -m marsha' in text
    assert '__MARSHA_VENV__' in text


def test_bat_launcher_uses_safe_path_flag() -> None:
    text = _template('marsha.bat.in')
    assert '-P -m marsha' in text
    assert '__MARSHA_VENV__' in text
